FROM gcc:13
WORKDIR /app
COPY . .
RUN apt-get update && apt-get install -y libssl-dev make && apt-get clean
RUN make clean && make
CMD ["./hashfinder","-g","-f","rockyou/rockyou_100.txt","-o","t3c/rockyou_100.t3c"]
